name="usdc"
version="2.1"

[setting.tokenName]
defaultValue="USD Coin"

[setting.tokenSymbol]
defaultValue="USDC"

[setting.tokenCurrency]
defaultValue="USD"

[setting.tokenDecimals]
defaultValue="6"

[setting.newPauser]
defaultValue="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.newBlacklister]
defaultValue="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.newOwner]
defaultValue="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.lostAndFound]
defaultValue="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.minterManager]
defaultValue="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[contract.MasterMinter]
artifact="MasterMinter"
args=["<%= settings.minterManager %>"]

[contract.FiatTokenV2_1]
artifact="FiatTokenV2_1"
depends=['contract.MasterMinter']

[contract.FiatTokenProxy]
artifact="FiatTokenProxy"
args=["<%= contracts.FiatTokenV2_1.address %>"]
abiOf=["FiatTokenV2_1"]
depends=['contract.FiatTokenV2_1']

[invoke.initialize]
target=["FiatTokenProxy"]
func="initialize"
args=[
"<%= settings.tokenName %>",
"<%= settings.tokenSymbol %>",
"<%= settings.tokenCurrency %>",
"<%= settings.tokenDecimals %>",
"<%= contracts.MasterMinter.address %>",
"<%= settings.newPauser %>",
"<%= settings.newBlacklister %>",
"<%= settings.newOwner %>"
]
depends=['contract.FiatTokenProxy']

[invoke.initializeV2]
target=["FiatTokenProxy"]
func="initializeV2"
args=['<%= settings.newName =>']
depends=['invoke.initialize']

[invoke.initializeV2_1]
target=["FiatTokenProxy"]
func="initializeV2_1"
args=['<%= settings.lostAndFound %>']
depends=['invoke.initializeV2']
